services:
  nginx:
    image: nginx:stable
    container_name: automa-nginx
    environment:
      VIRTUAL_HOST: automa.lcl
      VIRTUAL_PORT: 80
      VIRTUAL_PROTO: http
    expose:
      - "80"
      - "443"
    volumes:
      - ./:/usr/share/nginx/html:cached
    networks:
      - automa-net
      - proxy-net  # attach to vhost-proxy network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  automa-net:
    driver: bridge
    name: automa-net
  proxy-net:
    external: true
    name: proxy-net
